[package]
name = "napkin-benches"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "collections"
harness = false

[[bench]]
name = "memory_access"
harness = false

[dependencies]
criterion = "0.5.1"
rand = "0.9.1"
rustc-hash = "2.1.1"
smallvec = "1.15.0"
dashmap = "6.1.0"
indexmap = "2.9.0"
